# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  # config.vm.box = "devalone-ubuntu-20.04-server-x64"
  # config.vm.box = "devalone-ubuntu-20.04-server-x64-puppet"
  config.vm.box = "devalone/ubuntu-20.04-server-x64-puppet"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.network "public_network", ip: "192.168.0.2", hostname: true
  config.vm.hostname = "dnsmasq.sansovo.org"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # name this virtual machine
    vb.name = "dnsmasq"
    #   # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    #
    #   # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.cpus = 2
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  # vagrant file
  config.vm.provision "file", source: "./files", destination: "/tmp/"

  # shell bootstrap
  config.vm.provision "bootstrap", type: "shell", privileged: true do |s|
    s.inline = $bootstrap
  end

  # shell set puppet server config, 只手动执行，避免重复执行私钥不匹配:
  #
  # vagrant provision --provision-with set-puppet-server
  #
  config.vm.provision "set-puppet-server", type: "shell", run: "never", privileged: true do |s|
    s.inline = $set_puppet_server
  end

  # puppet apply resolved module
  config.vm.provision :puppet do |puppet|
    # apply module_path
    puppet.module_path = ["../puppet/puppet-modules"]

    # apply mainifest_file
    puppet.manifests_path = "puppet/puppet-apply/dnsclient/manifests"
    # puppet.manifest_file = "dnsclient.pp"
    puppet.manifest_file = "dns_resolved.pp"

    # apply environment
    # puppet.environment_path = "puppet/environments"
    # puppet.environment = "production"

    puppet.options = "--test --verbose"
  end

  # shell seperator print
  config.vm.provision "seperator1", type: "shell", privileged: true do |s|
    s.inline = $seperator1
  end

  # puppet apply dnsmasq module
  config.vm.provision :puppet do |puppet|
    # apply module_path
    puppet.module_path = ["puppet/modules"]

    # apply mainifest_file
    puppet.manifests_path = "puppet/puppet-apply/dnsmasq/manifests"
    puppet.manifest_file = "dnsmasq.pp"

    puppet.options = "--test --verbose"
  end

  # shell seperator print
  config.vm.provision "seperator2", type: "shell", privileged: true do |s|
    s.inline = $seperator2
  end

  # puppet apply ntp module
  config.vm.provision :puppet do |puppet|
    # apply module_path
    puppet.module_path = ["puppet/modules"]

    # apply mainifest_file
    puppet.manifests_path = "puppet/puppet-apply/ntp/manifests"
    puppet.manifest_file = "ntp.pp"

    puppet.options = "--test --verbose"
  end

  # shell end
  config.vm.provision "end", type: "shell", privileged: true, run: "always" do |s|
    s.inline = $end
  end
end

$bootstrap = <<-SCRIPT
mv /tmp/files/hosts /etc/hosts
mv /tmp/files/resolv.conf.dnsmasq /etc/resolv.conf.dnsmasq
systemctl stop puppet.service
apt-get update
apt-get install --only-upgrade puppet-agent
source /etc/profile.d/puppet-agent.sh
puppet config set server puppetserver.sansovo.org --section main
puppet ssl bootstrap
SCRIPT

# set puppet server shell script
$set_puppet_server = <<-SCRIPT
puppet config set server puppetserver.sansovo.org --section main
SCRIPT

$seperator1 = <<-SCRIPT
echo 'puppet resolved module complete.'
SCRIPT

$seperator2 = <<-SCRIPT
echo 'puppet dnsmasq module complete.'
SCRIPT

$end = <<-SCRIPT
apt-get clean
sudo systemctl restart dnsmasq.service
SCRIPT

# puppet ssl bootstrap
